# $HOME/.config/fish/conf.d/03_abbreviations.fish
abbr lg "lazygit"
abbr yy "yazi"
abbr ag "aichat"
abbr czz "chezmoi cd"
abbr czd "chezmoi diff"
abbr cza "chezmoi apply"
abbr ta "tmux a -t"
abbr tn "tmux new-session -t"
abbr fr "fish_reload"
abbr up "tools_update"
abbr upa "tools_update --all"
