# ~/.config/fish/conf.d/03_abbreviations.fish
abbr lg "lazygit"
abbr yy "yazi"
abbr ag "aichat"
abbr scrpy "scripts_python"
abbr czz "chezmoi cd"
abbr czd "chezmoi diff"
abbr cza "chezmoi apply"
abbr ta "tmux a -t "
abbr tn "tmux new-session -t "
