[project]
name = "torch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.8.20"
dependencies = [
    "setuptools>=75.3.2",
    "torch==1.13.1",
    "torchvision==0.14.1",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu117", marker = "sys_platform == 'linux'" },
]
torchvision = [
  { index = "pytorch-cu117", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu117"
url = "https://download.pytorch.org/whl/cu117"
explicit = true




