[project]
name = "diffusion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "ninja>=1.11.1.4",
    "opencv-python>=4.11.0.86",
    "setuptools>=80.9.0",
    "torch==2.4.1",
    "torchvision==0.19.1",
    "xformers==0.0.28.post1",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu118-nju", marker = "sys_platform == 'linux'" },
]
torchvision = [
  { index = "pytorch-cu118-nju", marker = "sys_platform == 'linux'" },
]
xformers = [
  { index = "pytorch-cu118-nju", marker = "sys_platform == 'linux'" },
]
[[tool.uv.index]]
name = "pytorch-cu118-nju"
url = "https://mirrors.nju.edu.cn/pytorch/whl/cu118/"
explicit = true
